export default [
  {
    "id": 1,
    "node_id": "MDExOkdpc3RDb21tZW50MQ==",
    "url": "https://api.github.com/gists/a6db0bec360bb87e9418/comments/1",
    "body": "Just commenting for the sake of commenting",
    "user": {
      "login": "octocat",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-04-18T23:23:56Z",
    "updated_at": "2011-04-18T23:23:56Z"
  },
  {
    "url": "https://api.github.com/gists/34f46e1723a2118bb16190c22dbed1cc/comments/2322065",
    "id": 2322065,
    "node_id": "MDExOkdpc3RDb21tZW50MzRmNDZlMTcyM2EyMTE4YmIxNjE5MGMyMmRiZWQxY2M6MjMyMjA2NQ==",
    "user": {
      "login": "drwhitehouse",
      "id": 8874233,
      "node_id": "MDQ6VXNlcjg4NzQyMzM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8874233?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/drwhitehouse",
      "html_url": "https://github.com/drwhitehouse",
      "followers_url": "https://api.github.com/users/drwhitehouse/followers",
      "following_url": "https://api.github.com/users/drwhitehouse/following{/other_user}",
      "gists_url": "https://api.github.com/users/drwhitehouse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/drwhitehouse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/drwhitehouse/subscriptions",
      "organizations_url": "https://api.github.com/users/drwhitehouse/orgs",
      "repos_url": "https://api.github.com/users/drwhitehouse/repos",
      "events_url": "https://api.github.com/users/drwhitehouse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/drwhitehouse/received_events",
      "type": "User",
      "site_admin": false
    },
    "author_association": "NONE",
    "created_at": "2018-01-16T00:48:46Z",
    "updated_at": "2018-01-16T00:48:46Z",
    "body": "This works well for me with High Sierra and not so well with iOS 11.2.2 still troubleshooting atm."
  },
  {
    "url": "https://api.github.com/gists/34f46e1723a2118bb16190c22dbed1cc/comments/2269457",
    "id": 2269457,
    "node_id": "MDExOkdpc3RDb21tZW50MzRmNDZlMTcyM2EyMTE4YmIxNjE5MGMyMmRiZWQxY2M6MjI2OTQ1Nw==",
    "user": {
      "login": "Paulmulonzia",
      "id": 34029747,
      "node_id": "MDQ6VXNlcjM0MDI5NzQ3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/34029747?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Paulmulonzia",
      "html_url": "https://github.com/Paulmulonzia",
      "followers_url": "https://api.github.com/users/Paulmulonzia/followers",
      "following_url": "https://api.github.com/users/Paulmulonzia/following{/other_user}",
      "gists_url": "https://api.github.com/users/Paulmulonzia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Paulmulonzia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Paulmulonzia/subscriptions",
      "organizations_url": "https://api.github.com/users/Paulmulonzia/orgs",
      "repos_url": "https://api.github.com/users/Paulmulonzia/repos",
      "events_url": "https://api.github.com/users/Paulmulonzia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Paulmulonzia/received_events",
      "type": "User",
      "site_admin": false
    },
    "author_association": "NONE",
    "created_at": "2017-11-27T12:37:39Z",
    "updated_at": "2017-11-27T12:37:39Z",
    "body": "When I try to run Ipsec up roadwarrior, I keep getting this error:   unable to resolve %any, initiate aborted\r\ntried to check-in and delete nonexisting IKE_SA\r\nestablishing connection 'roadwarrior' failed.\r\nWhat could be the problem\r\n"
  },
  {
    "url": "https://api.github.com/gists/34f46e1723a2118bb16190c22dbed1cc/comments/2673554",
    "id": 2673554,
    "node_id": "MDExOkdpc3RDb21tZW50MzRmNDZlMTcyM2EyMTE4YmIxNjE5MGMyMmRiZWQxY2M6MjY3MzU1NA==",
    "user": {
      "login": "gitbls",
      "id": 10481163,
      "node_id": "MDQ6VXNlcjEwNDgxMTYz",
      "avatar_url": "https://avatars2.githubusercontent.com/u/10481163?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gitbls",
      "html_url": "https://github.com/gitbls",
      "followers_url": "https://api.github.com/users/gitbls/followers",
      "following_url": "https://api.github.com/users/gitbls/following{/other_user}",
      "gists_url": "https://api.github.com/users/gitbls/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gitbls/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gitbls/subscriptions",
      "organizations_url": "https://api.github.com/users/gitbls/orgs",
      "repos_url": "https://api.github.com/users/gitbls/repos",
      "events_url": "https://api.github.com/users/gitbls/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gitbls/received_events",
      "type": "User",
      "site_admin": false
    },
    "author_association": "NONE",
    "created_at": "2018-08-08T18:11:16Z",
    "updated_at": "2018-08-08T18:11:16Z",
    "body": "I missed your point that the CA cert needed to be loaded onto the iDevice as well as the user cert. Once I loaded the CA cert, everything works fine. This is SO much better than using mobileconfig!"
  },
  {
    "url": "https://api.github.com/gists/34f46e1723a2118bb16190c22dbed1cc/comments/2667387",
    "id": 2667387,
    "node_id": "MDExOkdpc3RDb21tZW50MzRmNDZlMTcyM2EyMTE4YmIxNjE5MGMyMmRiZWQxY2M6MjY2NzM4Nw==",
    "user": {
      "login": "malaiwah",
      "id": 10375593,
      "node_id": "MDQ6VXNlcjEwMzc1NTkz",
      "avatar_url": "https://avatars2.githubusercontent.com/u/10375593?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/malaiwah",
      "html_url": "https://github.com/malaiwah",
      "followers_url": "https://api.github.com/users/malaiwah/followers",
      "following_url": "https://api.github.com/users/malaiwah/following{/other_user}",
      "gists_url": "https://api.github.com/users/malaiwah/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/malaiwah/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/malaiwah/subscriptions",
      "organizations_url": "https://api.github.com/users/malaiwah/orgs",
      "repos_url": "https://api.github.com/users/malaiwah/repos",
      "events_url": "https://api.github.com/users/malaiwah/events{/privacy}",
      "received_events_url": "https://api.github.com/users/malaiwah/received_events",
      "type": "User",
      "site_admin": false
    },
    "author_association": "NONE",
    "created_at": "2018-08-02T20:27:04Z",
    "updated_at": "2018-08-02T20:27:04Z",
    "body": "I was on debian and strongswan/charon are quite modularized. I was getting:\r\n\r\nAug  2 20:12:52 vpnmaster charon: 11[IKE] EAP-Identity request configured, but not supported\r\nAug  2 20:12:52 vpnmaster charon: 11[IKE] loading EAP_TLS method failed\r\n\r\nTurns out I had to install libcharon-extra-plugins (https://packages.debian.org/sid/libcharon-extra-plugins) to make it work."
  }
];